#!/usr/bin/env python3
"""Deep ZUGFeRD / XRechnung validation for the Event Central invoice fuzzer.

``generate_invoices.py`` already does *shallow* document checks: it confirms the
returned ``invoicePdf`` / ``invoiceXml`` are valid base64, that the PDF starts
with ``%PDF`` and that the XML is well-formed. That catches gross breakage but
says nothing about whether the documents are *actually* conformant e-invoices.

This module adds the deep check by calling a dockerized validator over HTTP
(see ``docker-compose.yml`` -- the Mustangproject engine, which validates the
WHOLE ZUGFeRD/Factur-X PDF: PDF/A-3 conformance + the embedded XML against
XML-Schema and the EN16931 / profile Schematron, plus stand-alone XRechnung/CII
XML). Findings are folded into the fuzzer's existing ``Report`` so a
non-conformant document generated by the API shows up as a normal failure.

How to use it
-------------
1. In ``generate_invoices.py``, import this module once, then call the two
   functions where the 201 response is checked (inside ``_validate_success``),
   passing the response fields and the ``Report``::

       from src import validate_invoices        # or: import validate_invoices

       # ... in _validate_success(data, resp, report): ...
       validate_invoices.validate_zugferd(data.get("invoicePdf"), report)
       validate_invoices.validate_xrechnung(data.get("invoiceXml"), report)

   Each runs the cheap structural checks then the deep HTTP validation and folds
   any findings into ``report`` (and returns a ``ValidationOutcome``). They fully
   replace the module's original ``_validate_pdf`` / ``_validate_xml`` calls.

2. Standalone, over already-saved outputs::

       python -m src.validate_invoices invoices/            # a directory
       python -m src.validate_invoices some-invoice.pdf ...  # explicit files

Configuration (environment variables)
    INVOICE_VALIDATOR_URL       default http://localhost:7470
    INVOICE_VALIDATOR_REQUIRED  "1" -> a validator that is down/unreachable is a
                                hard error; default "0" -> degrade to a warning
                                and keep the fuzzer running.
    INVOICE_VALIDATOR_NOTICES   "1" -> surface NOTICE-level findings too.
    INVOICE_VALIDATOR_TIMEOUT   per-request HTTP timeout in seconds (default 150).
"""

from __future__ import annotations

import base64
import os
import sys
import threading
from dataclasses import dataclass, field
from typing import Any
from xml.etree import ElementTree

import requests

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

VALIDATOR_URL = os.environ.get(
    "INVOICE_VALIDATOR_URL", "http://localhost:7470").rstrip("/")
VALIDATOR_REQUIRED = os.environ.get(
    "INVOICE_VALIDATOR_REQUIRED", "0") in ("1", "true", "yes")
INCLUDE_NOTICES = os.environ.get(
    "INVOICE_VALIDATOR_NOTICES", "0") in ("1", "true", "yes")
# A whole-PDF validation (veraPDF + Schematron) can take a while on a cold JVM,
# so allow more than the shim's own VALIDATE_TIMEOUT for the round trip.
HTTP_TIMEOUT = int(os.environ.get("INVOICE_VALIDATOR_TIMEOUT", "150"))


# --------------------------------------------------------------------------- #
# Result model
# --------------------------------------------------------------------------- #

@dataclass
class Finding:
    """One rule result from the validator (an error, warning or notice)."""
    severity: str          # "error" | "warning" | "notice"
    message: str
    code: str = ""         # e.g. "BR-16", "18", "23" (rule / Mustang error type)
    section: str = ""      # "pdf" | "xml" | ""
    location: str = ""     # XPath, when the engine reports one

    def one_line(self) -> str:
        where = f"[{self.section}]" if self.section else ""
        code = f" {self.code}" if self.code else ""
        return f"{where}{code} {self.message}".strip()


@dataclass
class ValidationOutcome:
    """Structured result of validating a single document."""
    # True/False = a real verdict from the engine; None = we could not get one
    # (validator down, transport error, etc.) and the caller should degrade.
    valid: bool | None
    engine: str = "mustang"
    section_status: dict[str, str] = field(default_factory=dict[str, str])
    findings: list[Finding] = field(default_factory=list[Finding])
    report_xml: str = ""
    transport_error: str | None = None   # set when valid is None

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "error"]

    @property
    def warnings(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "warning"]


# --------------------------------------------------------------------------- #
# Report parsing (Mustang <validation> XML)
# --------------------------------------------------------------------------- #

# Mustang error "type" codes that concern the PDF container rather than a
# business rule -- useful for a friendlier label, purely cosmetic.
_MUSTANG_PDF_ERROR_TYPES = {"23", "24", "25", "26", "27"}


def _extract_code(text: str, elem_type: str) -> str:
    """Pull a rule id like ``BR-16`` / ``PEPPOL-EN16931-R008`` from the message,
    falling back to Mustang's numeric ``type`` attribute."""
    t = text.strip()
    if t.startswith("["):
        end = t.find("]")
        if end != -1:
            return t[1:end]
    return elem_type or ""


def _clean_message(text: str, code: str) -> str:
    """Tidy a raw rule message: drop the leading ``[CODE]-`` (we surface the code
    separately) and the trailing ``from /xslt/....xslt)`` engine breadcrumb."""
    t = " ".join(text.split())  # collapse whitespace/newlines
    if code and t.startswith(f"[{code}]"):
        t = t[len(code) + 2:].lstrip("-").strip()
    lower = t.lower()
    marker = " from /xslt/"
    idx = lower.find(marker)
    if idx != -1:
        t = t[:idx].rstrip()
        if t.endswith(("(", "from")):
            t = t.rstrip("(from ").rstrip()
    return t


def parse_mustang_report(report_xml: str) -> ValidationOutcome:
    """Parse a Mustang ``<validation>`` report into a :class:`ValidationOutcome`.

    The report has an optional ``<pdf>`` section (veraPDF PDF/A result) and/or an
    ``<xml>`` section (schema + Schematron), each carrying a ``<messages>`` block
    of ``<error>`` / ``<warning>`` / ``<notice>`` elements and a per-section
    ``<summary status="valid|invalid"/>``. A top-level ``<summary>`` gives the
    overall verdict.
    """
    try:
        root = ElementTree.fromstring(report_xml)
    except ElementTree.ParseError as exc:
        return ValidationOutcome(
            valid=None, report_xml=report_xml,
            transport_error=f"could not parse validator report: {exc}")

    findings: list[Finding] = []
    section_status: dict[str, str] = {}

    for section_name in ("pdf", "xml"):
        section = root.find(section_name)
        if section is None:
            continue
        summ = section.find("summary")
        if summ is not None and summ.get("status"):
            section_status[section_name] = summ.get("status", "")
        messages = section.find("messages")
        if messages is None:
            continue
        for elem in messages:
            severity = elem.tag.lower()      # error | warning | notice
            if severity not in ("error", "warning", "notice"):
                continue
            text = (elem.text or "").strip()
            code = _extract_code(text, elem.get("type", ""))
            findings.append(Finding(
                severity=severity,
                message=_clean_message(text, code),
                code=code,
                section=section_name,
                location=elem.get("location", ""),
            ))

    # Overall verdict: the last top-level <summary> (Mustang emits section
    # summaries first, then the overall one).
    overall = None
    for summ in root.findall("summary"):
        status = summ.get("status")
        if status:
            overall = status.lower() == "valid"
    if overall is None and section_status:
        overall = all(v.lower() == "valid" for v in section_status.values())

    return ValidationOutcome(
        valid=overall,
        section_status=section_status,
        findings=findings,
        report_xml=report_xml,
    )


# --------------------------------------------------------------------------- #
# HTTP client
# --------------------------------------------------------------------------- #

class InvoiceValidatorClient:
    """Thin HTTP client for the dockerized Mustang validator."""

    def __init__(self, base_url: str = VALIDATOR_URL,
                 timeout: int = HTTP_TIMEOUT,
                 session: requests.Session | None = None):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = session or requests.Session()

    def health(self) -> bool:
        try:
            r = self.session.get(f"{self.base_url}/health", timeout=5)
            return r.status_code == 200
        except requests.RequestException:
            return False

    def validate_bytes(self, raw: bytes, *, kind: str | None = None,
                        notices: bool = INCLUDE_NOTICES) -> ValidationOutcome:
        """Validate raw PDF or XML bytes. ``kind`` is auto-sniffed if omitted."""
        params: dict[str, str] = {"notices": "1" if notices else "0"}
        if kind:
            params["kind"] = kind
        try:
            r = self.session.post(
                f"{self.base_url}/validate",
                params=params,
                data=raw,
                headers={"Content-Type": "application/octet-stream"},
                timeout=self.timeout,
            )
        except requests.RequestException as exc:
            return ValidationOutcome(
                valid=None, transport_error=f"validator unreachable: {exc}")

        if r.status_code != 200:
            detail = ""
            try:
                detail = r.json().get("error", "")
            except ValueError:
                detail = r.text[:200]
            return ValidationOutcome(
                valid=None,
                transport_error=f"validator HTTP {r.status_code}: {detail}")

        payload: dict[str, Any] = r.json()
        outcome = parse_mustang_report(payload.get("report_xml", ""))
        # Prefer the parsed verdict; fall back to the server's boolean.
        if outcome.valid is None:
            outcome.valid = bool(payload.get("valid"))
        outcome.engine = payload.get("engine", "mustang")
        return outcome


# A process-wide default client so the validate_* helpers are cheap to call.
_default_client: InvoiceValidatorClient | None = None
_client_lock = threading.Lock()
# We only want to nag once about a down validator, not per invoice.
_unavailable_warned = False


def get_client() -> InvoiceValidatorClient:
    global _default_client
    with _client_lock:
        if _default_client is None:
            _default_client = InvoiceValidatorClient()
        return _default_client


# --------------------------------------------------------------------------- #
# Folding an outcome into the fuzzer's Report
# --------------------------------------------------------------------------- #

def _apply_outcome(outcome: ValidationOutcome, report: Any, *, doc: str) -> None:
    """Merge a :class:`ValidationOutcome` into a fuzzer ``Report``.

    ``report`` is the ``generate_invoices.Report`` dataclass (duck-typed here to
    avoid a hard import cycle): it exposes ``.errors``, ``.warnings`` and
    ``.anomalies`` lists.

    Severity policy mirrors the fuzzer's own: a *clean* invoice (no recorded
    anomalies) that the validator rejects is a generator bug -> error. On an
    *edge* invoice we deliberately sent something odd, so a rejection is expected
    -> record it as a warning to keep the signal clean.
    """
    global _unavailable_warned

    # Transport / availability problems: not an invoice verdict.
    if outcome.valid is None:
        msg = f"{doc}: deep validation unavailable ({outcome.transport_error})"
        if VALIDATOR_REQUIRED:
            report.errors.append(msg)
        elif not _unavailable_warned:
            _unavailable_warned = True
            report.warnings.append(
                msg + " -- set INVOICE_VALIDATOR_REQUIRED=1 to treat as error, "
                "or start it with `docker compose up -d`")
        return

    is_edge = bool(getattr(report, "anomalies", None))

    # Emit each finding. Errors on a clean invoice stay errors; on an edge
    # invoice they are downgraded to warnings (expected fallout).
    for f in outcome.findings:
        line = f"{doc}: {f.one_line()}"
        if f.severity == "error":
            (report.warnings if is_edge else report.errors).append(line)
        elif f.severity == "warning":
            report.warnings.append(line)
        elif INCLUDE_NOTICES:
            report.warnings.append(line)

    # If the engine says "invalid" but produced no error-level messages (e.g. a
    # PDF/A container failure surfaced only in the summary), make sure the
    # verdict is not silently lost.
    if outcome.valid is False and not outcome.errors:
        line = (f"{doc}: validator verdict INVALID "
                f"(sections={outcome.section_status or 'n/a'})")
        (report.warnings if is_edge else report.errors).append(line)


# --------------------------------------------------------------------------- #
# Public validation entry points
# --------------------------------------------------------------------------- #
# Call these from generate_invoices.py. They accept the value straight from the
# API response (a base64 string) or raw bytes, run the cheap structural checks
# first, then the deep HTTP validation, and fold any findings into ``report``
# (when given). Each also returns the ValidationOutcome for standalone use.

def _coerce_bytes(document: Any) -> tuple[bytes | None, str | None, str | None]:
    """Normalize a response value to raw bytes.

    Returns ``(raw, warning, error)``: exactly one of the three is meaningful.
    ``warning`` means "nothing to validate" (missing field); ``error`` means the
    value was present but unusable (bad base64 / wrong type).
    """
    if document is None or document == "":
        return None, "missing from response", None
    if isinstance(document, (bytes, bytearray)):
        return bytes(document), None, None
    if isinstance(document, str):
        try:
            return base64.b64decode(document, validate=True), None, None
        except Exception:
            return None, None, "is not valid base64"
    return None, None, f"has unexpected type {type(document).__name__}"


def _early(report: Any, *, doc: str, section: str,
           warning: str | None = None, error: str | None = None) -> ValidationOutcome:
    """Record a pre-check result and build the matching outcome.

    ``warning`` means "nothing to validate" (missing field) -> no verdict;
    ``error`` means the value was present but unusable -> invalid.
    """
    if warning is not None:
        msg = f"{doc}: {warning}"
        if report is not None:
            report.warnings.append(msg)
        return ValidationOutcome(
            valid=None,
            findings=[Finding("warning", msg, section=section)])
    msg = f"{doc}: {error}"
    if report is not None:
        report.errors.append(msg)
    return ValidationOutcome(
        valid=False,
        findings=[Finding("error", msg, section=section)])


def validate_zugferd(pdf: Any, report: Any = None, *,
                     client: InvoiceValidatorClient | None = None) -> ValidationOutcome:
    """Validate a ZUGFeRD / Factur-X document -- the WHOLE hybrid PDF.

    Checks PDF/A-3 conformance *and* the embedded XML (XML-Schema + EN16931 /
    profile Schematron), i.e. the file, not just the data.

    ``pdf``    the ``invoicePdf`` value from the API response (base64 string) or
               raw PDF bytes.
    ``report`` optional fuzzer ``Report``; when given, findings are appended to
               ``report.errors`` / ``report.warnings`` (severity follows the
               fuzzer's clean-vs-edge policy). The ``ValidationOutcome`` is
               always returned as well.
    """
    raw, warn, err = _coerce_bytes(pdf)
    if warn:
        return _early(report, doc="invoicePdf", section="pdf", warning=warn)
    if err:
        return _early(report, doc="invoicePdf", section="pdf", error=err)
    if raw is None:
        return _early(report, doc="invoicePdf", section="pdf",
                      error="Raw value is None")
    if not raw.startswith(b"%PDF"):
        return _early(report, doc="invoicePdf", section="pdf",
                      error="does not start with %PDF")
    outcome = (client or get_client()).validate_bytes(raw, kind="pdf")
    if report is not None:
        _apply_outcome(outcome, report, doc="invoicePdf")
    return outcome


def validate_xrechnung(xml: Any, report: Any = None, *,
                       client: InvoiceValidatorClient | None = None) -> ValidationOutcome:
    """Validate an XRechnung / CII XML document (schema + EN16931 / profile).

    ``xml``    the ``invoiceXml`` value from the API response (base64 string) or
               raw XML bytes.
    ``report`` optional fuzzer ``Report`` (see :func:`validate_zugferd`).
    """
    raw, warn, err = _coerce_bytes(xml)
    if warn:
        return _early(report, doc="invoiceXml", section="xml", warning=warn)
    if err:
        return _early(report, doc="invoiceXml", section="xml", error=err)
    if raw is None:
        return _early(report, doc="invoiceXml", section="xml", error="Raw value is None")
    try:
        ElementTree.fromstring(raw)
    except ElementTree.ParseError as exc:
        return _early(report, doc="invoiceXml", section="xml",
                      error=f"is not well-formed XML: {exc}")
    outcome = (client or get_client()).validate_bytes(raw, kind="xml")
    if report is not None:
        _apply_outcome(outcome, report, doc="invoiceXml")
    return outcome


# --------------------------------------------------------------------------- #
# Standalone CLI: validate files or directories directly
# --------------------------------------------------------------------------- #

def _validate_path(path: str, client: InvoiceValidatorClient) -> ValidationOutcome:
    with open(path, "rb") as fh:
        raw = fh.read()
    kind = "pdf" if raw.startswith(b"%PDF") else "xml"
    return client.validate_bytes(raw, kind=kind)


def _iter_targets(paths: list[str]) -> list[str]:
    import glob
    out: list[str] = []
    for p in paths:
        if os.path.isdir(p):
            for ext in ("*.pdf", "*.xml"):
                out.extend(sorted(glob.glob(os.path.join(p, "**", ext),
                                            recursive=True)))
        else:
            out.append(p)
    return out


def _main(argv: list[str]) -> int:
    import argparse
    parser = argparse.ArgumentParser(
        description="Validate ZUGFeRD/Factur-X PDFs or XRechnung/CII XML files "
                    "against the dockerized Mustang validator.")
    parser.add_argument("paths", nargs="+",
                        help="files and/or directories to validate")
    parser.add_argument("--url", default=VALIDATOR_URL,
                        help=f"validator base URL (default {VALIDATOR_URL})")
    parser.add_argument("--notices", action="store_true",
                        help="include NOTICE-level findings")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="print every finding, not just a summary line")
    args = parser.parse_args(argv)

    client = InvoiceValidatorClient(base_url=args.url)
    if not client.health():
        print(f"validator at {client.base_url} is not reachable. "
              f"Start it with: docker compose up -d --build", file=sys.stderr)
        return 2

    targets = _iter_targets(args.paths)
    if not targets:
        print("no .pdf/.xml files found", file=sys.stderr)
        return 2

    bad = 0
    for path in targets:
        try:
            outcome = _validate_path(path, client)
        except OSError as exc:
            print(f"SKIP  {path}: {exc}")
            continue
        if outcome.valid is None:
            print(f"ERR   {path}: {outcome.transport_error}")
            bad += 1
            continue
        tag = "VALID  " if outcome.valid else "INVALID"
        n_err = len(outcome.errors)
        n_warn = len(outcome.warnings)
        print(f"{tag} {path}  (errors={n_err} warnings={n_warn} "
              f"sections={outcome.section_status or '-'})")
        if not outcome.valid:
            bad += 1
        if args.verbose or (not outcome.valid and not args.verbose):
            shown = outcome.findings if args.verbose else outcome.errors
            for f in shown:
                print(f"        {f.one_line()}")
    print(f"\n{len(targets)} file(s), {bad} invalid/unvalidatable")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))