#!/usr/bin/env python3
"""Deep ZUGFeRD / XRechnung validation for the Event Central invoice fuzzer.

``generate_invoices.py`` already does *shallow* document checks: it confirms the
returned ``invoicePdf`` / ``invoiceXml`` are valid base64, that the PDF starts
with ``%PDF`` and that the XML is well-formed. That catches gross breakage but
says nothing about whether the documents are *actually* conformant e-invoices.

This module adds the deep check by calling two dockerized validators over HTTP
(see ``docker-compose.yml``):

  * Mustang (:8088) validates the WHOLE ZUGFeRD/Factur-X PDF -- PDF/A-3
    conformance + the embedded XML against XML-Schema and the EN16931 / profile
    Schematron. It can also extract the embedded XML from a PDF.
  * KoSIT (:8089), the official German B2G reference validator, validates
    XRechnung / CII XML against EN16931 and the XRechnung CIUS (BR-DE) rules.

How the two functions use them:

  * ``validate_xrechnung(xml, report)`` -> KoSIT (authoritative for the XML).
  * ``validate_zugferd(pdf, report)``   -> Mustang on the whole PDF (primary);
    then the embedded XML is extracted and also run through KoSIT as a secondary
    second opinion (folded in as warnings; a plain ZUGFeRD CII that is not an
    XRechnung matches no scenario and is treated as a notice, not a failure).

Findings are folded into the fuzzer's existing ``Report`` so a non-conformant
document generated by the API shows up as a normal failure.

How to use it
-------------
1. In ``generate_invoices.py``, import this module once, then call the two
   functions where the 201 response is checked (inside ``_validate_success``),
   passing the response fields and the ``Report``::

       from src import validate_invoices        # or: import validate_invoices

       # ... in _validate_success(data, resp, report): ...
       validate_invoices.validate_zugferd(data.get("invoicePdf"), report)
       validate_invoices.validate_xrechnung(data.get("invoiceXml"), report)

   Each runs the cheap structural checks then the deep HTTP validation and folds
   any findings into ``report`` (and returns a ``ValidationOutcome``). They fully
   replace the module's original ``_validate_pdf`` / ``_validate_xml`` calls.

2. Standalone, over already-saved outputs::

       python -m src.validate_invoices invoices/            # a directory
       python -m src.validate_invoices some-invoice.pdf ...  # explicit files

Configuration (environment variables)
    INVOICE_VALIDATOR_MUSTANG_URL       Mustang base URL, default http://localhost:8088
    INVOICE_VALIDATOR_KOSIT_URL           KoSIT base URL,   default http://localhost:8089
    INVOICE_VALIDATOR_REQUIRED  "1" -> a validator that is down/unreachable is a
                                hard error; default "0" -> degrade to a warning
                                and keep the fuzzer running. (Secondary KoSIT on
                                the embedded XML never hard-fails.)
    INVOICE_VALIDATOR_NOTICES   "1" -> surface NOTICE-level findings too.
    INVOICE_VALIDATOR_TIMEOUT   per-request HTTP timeout in seconds (default 150).
"""

from __future__ import annotations

import base64
import os
import sys
import threading
from dataclasses import dataclass, field
from typing import Any
from xml.etree import ElementTree

import requests

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

MUSTANG_URL = os.environ.get(
    "INVOICE_VALIDATOR_MUSTANG_URL", "http://localhost:7470").rstrip("/")
# KoSIT XRechnung validator (official reference; German CIUS / BR-DE rules).
KOSIT_URL = os.environ.get(
    "INVOICE_VALIDATOR_KOSIT_URL", "http://localhost:7471").rstrip("/")
VALIDATOR_REQUIRED = os.environ.get(
    "INVOICE_VALIDATOR_REQUIRED", "0") in ("1", "true", "yes")
INCLUDE_NOTICES = os.environ.get(
    "INVOICE_VALIDATOR_NOTICES", "0") in ("1", "true", "yes")
# A whole-PDF validation (veraPDF + Schematron) can take a while on a cold JVM,
# so allow more than the shim's own VALIDATE_TIMEOUT for the round trip.
HTTP_TIMEOUT = int(os.environ.get("INVOICE_VALIDATOR_TIMEOUT", "150"))


# --------------------------------------------------------------------------- #
# Result model
# --------------------------------------------------------------------------- #

@dataclass
class Finding:
    """One rule result from the validator (an error, warning or notice)."""
    severity: str          # "error" | "warning" | "notice"
    message: str
    code: str = ""         # e.g. "BR-16", "18", "23" (rule / Mustang error type)
    section: str = ""      # "pdf" | "xml" | ""
    location: str = ""     # XPath, when the engine reports one

    def one_line(self) -> str:
        where = f"[{self.section}]" if self.section else ""
        code = f" {self.code}" if self.code else ""
        return f"{where}{code} {self.message}".strip()


@dataclass
class ValidationOutcome:
    """Structured result of validating a single document."""
    # True/False = a real verdict from the engine; None = we could not get one
    # (validator down, transport error, etc.) and the caller should degrade.
    valid: bool | None
    engine: str = "mustang"
    section_status: dict[str, str] = field(default_factory=dict[str, str])
    findings: list[Finding] = field(default_factory=list[Finding])
    report_xml: str = ""
    transport_error: str | None = None   # set when valid is None
    # KoSIT only: False when the document matched no scenario (e.g. a plain
    # ZUGFeRD CII that is not an XRechnung); None for the Mustang engine.
    scenario_matched: bool | None = None

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "error"]

    @property
    def warnings(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "warning"]


# --------------------------------------------------------------------------- #
# Report parsing (Mustang <validation> XML)
# --------------------------------------------------------------------------- #

# Mustang error "type" codes that concern the PDF container rather than a
# business rule -- useful for a friendlier label, purely cosmetic.
_MUSTANG_PDF_ERROR_TYPES = {"23", "24", "25", "26", "27"}


def _extract_code(text: str, elem_type: str) -> str:
    """Pull a rule id like ``BR-16`` / ``PEPPOL-EN16931-R008`` from the message,
    falling back to Mustang's numeric ``type`` attribute."""
    t = text.strip()
    if t.startswith("["):
        end = t.find("]")
        if end != -1:
            return t[1:end]
    return elem_type or ""


def _clean_message(text: str, code: str) -> str:
    """Tidy a raw rule message: drop the leading ``[CODE]-`` (we surface the code
    separately) and the trailing ``from /xslt/....xslt)`` engine breadcrumb."""
    t = " ".join(text.split())  # collapse whitespace/newlines
    if code and t.startswith(f"[{code}]"):
        t = t[len(code) + 2:].lstrip("-").strip()
    lower = t.lower()
    marker = " from /xslt/"
    idx = lower.find(marker)
    if idx != -1:
        t = t[:idx].rstrip()
        if t.endswith(("(", "from")):
            t = t.rstrip("(from ").rstrip()
    return t


def parse_mustang_report(report_xml: str) -> ValidationOutcome:
    """Parse a Mustang ``<validation>`` report into a :class:`ValidationOutcome`.

    The report has an optional ``<pdf>`` section (veraPDF PDF/A result) and/or an
    ``<xml>`` section (schema + Schematron), each carrying a ``<messages>`` block
    of ``<error>`` / ``<warning>`` / ``<notice>`` elements and a per-section
    ``<summary status="valid|invalid"/>``. A top-level ``<summary>`` gives the
    overall verdict.
    """
    try:
        root = ElementTree.fromstring(report_xml)
    except ElementTree.ParseError as exc:
        return ValidationOutcome(
            valid=None, report_xml=report_xml,
            transport_error=f"could not parse validator report: {exc}")

    findings: list[Finding] = []
    section_status: dict[str, str] = {}

    for section_name in ("pdf", "xml"):
        section = root.find(section_name)
        if section is None:
            continue
        summ = section.find("summary")
        if summ is not None and summ.get("status"):
            section_status[section_name] = summ.get("status", "")
        messages = section.find("messages")
        if messages is None:
            continue
        for elem in messages:
            severity = elem.tag.lower()      # error | warning | notice
            if severity not in ("error", "warning", "notice"):
                continue
            text = (elem.text or "").strip()
            code = _extract_code(text, elem.get("type", ""))
            findings.append(Finding(
                severity=severity,
                message=_clean_message(text, code),
                code=code,
                section=section_name,
                location=elem.get("location", ""),
            ))

    # Overall verdict: the last top-level <summary> (Mustang emits section
    # summaries first, then the overall one).
    overall = None
    for summ in root.findall("summary"):
        status = summ.get("status")
        if status:
            overall = status.lower() == "valid"
    if overall is None and section_status:
        overall = all(v.lower() == "valid" for v in section_status.values())

    return ValidationOutcome(
        valid=overall,
        section_status=section_status,
        findings=findings,
        report_xml=report_xml,
    )


# --------------------------------------------------------------------------- #
# Report parsing (KoSIT VARL <rep:report> XML)
# --------------------------------------------------------------------------- #
# The KoSIT validator returns a VARL report:
#   <rep:report valid="true|false">
#     <engine><name>KoSIT Validator 1.6.2</name></engine>
#     <scenarioMatched> | <noScenarioMatched>
#        <validationStepResult id=... valid=...>
#           <message level="error|warning|information" code="BR-DE-1" xpathLocation=...>[BR-DE-1]-...</message>
#     <assessment><accept/> | <reject/></assessment>
# Namespaces vary, so we match by local tag name throughout.

_KOSIT_LEVEL = {"error": "error", "warning": "warning",
                "information": "notice", "info": "notice"}


def _local(elem: Any) -> str:
    return elem.tag.split("}")[-1]


def parse_kosit_report(report_xml: str) -> ValidationOutcome:
    """Parse a KoSIT VARL ``<rep:report>`` into a :class:`ValidationOutcome`."""
    try:
        root = ElementTree.fromstring(report_xml)
    except ElementTree.ParseError as exc:
        return ValidationOutcome(
            valid=None, engine="kosit", report_xml=report_xml,
            transport_error=f"could not parse KoSIT report: {exc}")

    valid = (root.get("valid") or "").strip().lower() == "true"

    scenario_matched: bool | None = None
    engine = "kosit"
    findings: list[Finding] = []
    section_status: dict[str, str] = {}

    for child in root:
        name = _local(child)
        if name == "engine":
            for e in child:
                if _local(e) == "name" and e.text:
                    engine = e.text.strip()
        elif name == "noScenarioMatched":
            scenario_matched = False
        elif name == "scenarioMatched":
            scenario_matched = True
            for vsr in child:
                if _local(vsr) != "validationStepResult":
                    continue
                step = vsr.get("id", "")
                if vsr.get("valid"):
                    section_status[step] = vsr.get("valid", "")
                for msg in vsr.iter():
                    if _local(msg) != "message":
                        continue
                    level = (msg.get("level") or "error").lower()
                    severity = _KOSIT_LEVEL.get(level, "error")
                    text = (msg.text or "").strip()
                    code = msg.get("code", "") or _extract_code(text, "")
                    findings.append(Finding(
                        severity=severity,
                        message=_clean_message(text, code),
                        code=code,
                        section="xml",
                        location=msg.get("xpathLocation", ""),
                    ))
        elif name == "assessment":
            for a in child:
                section_status["assessment"] = _local(a)  # accept | reject

    return ValidationOutcome(
        valid=valid,
        engine=engine,
        section_status=section_status,
        findings=findings,
        report_xml=report_xml,
        scenario_matched=scenario_matched,
    )


# --------------------------------------------------------------------------- #
# HTTP clients
# --------------------------------------------------------------------------- #

class InvoiceValidatorClient:
    """Thin HTTP client for the dockerized Mustang validator."""

    def __init__(self, base_url: str = MUSTANG_URL,
                 timeout: int = HTTP_TIMEOUT,
                 session: requests.Session | None = None):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = session or requests.Session()

    def health(self) -> bool:
        try:
            r = self.session.get(f"{self.base_url}/health", timeout=5)
            return r.status_code == 200
        except requests.RequestException:
            return False

    def validate_bytes(self, raw: bytes, *, kind: str | None = None,
                        notices: bool = INCLUDE_NOTICES) -> ValidationOutcome:
        """Validate raw PDF or XML bytes. ``kind`` is auto-sniffed if omitted."""
        params: dict[str, str] = {"notices": "1" if notices else "0"}
        if kind:
            params["kind"] = kind
        try:
            r = self.session.post(
                f"{self.base_url}/validate",
                params=params,
                data=raw,
                headers={"Content-Type": "application/octet-stream"},
                timeout=self.timeout,
            )
        except requests.RequestException as exc:
            return ValidationOutcome(
                valid=None, transport_error=f"validator unreachable: {exc}")

        if r.status_code != 200:
            detail = ""
            try:
                detail = r.json().get("error", "")
            except ValueError:
                detail = r.text[:200]
            return ValidationOutcome(
                valid=None,
                transport_error=f"validator HTTP {r.status_code}: {detail}")

        payload: dict[str, Any] = r.json()
        outcome = parse_mustang_report(payload.get("report_xml", ""))
        # Prefer the parsed verdict; fall back to the server's boolean.
        if outcome.valid is None:
            outcome.valid = bool(payload.get("valid"))
        outcome.engine = payload.get("engine", "mustang")
        return outcome

    def extract_embedded_xml(self, pdf: bytes) -> bytes | None:
        """Return the embedded Factur-X/ZUGFeRD XML of a PDF, or None.

        None means either "no XML embedded" or the extractor was unreachable;
        callers treat a missing secondary input as non-fatal.
        """
        try:
            r = self.session.post(
                f"{self.base_url}/extract",
                data=pdf,
                headers={"Content-Type": "application/octet-stream"},
                timeout=self.timeout,
            )
        except requests.RequestException:
            return None
        if r.status_code != 200:
            return None
        payload = r.json()
        if not payload.get("found"):
            return None
        try:
            return base64.b64decode(payload["xml_b64"], validate=True)
        except Exception:
            return None


class KositValidatorClient:
    """HTTP client for the dockerized official KoSIT XRechnung validator.

    Talks to the KoSIT daemon: ``POST /`` with the XML body returns a VARL
    ``<rep:report>``; ``GET /server/health`` is the liveness probe.
    """

    def __init__(self, base_url: str = KOSIT_URL,
                 timeout: int = HTTP_TIMEOUT,
                 session: requests.Session | None = None):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = session or requests.Session()

    def health(self) -> bool:
        try:
            r = self.session.get(f"{self.base_url}/server/health", timeout=5)
            return r.status_code == 200
        except requests.RequestException:
            return False

    def validate_bytes(self, raw: bytes) -> ValidationOutcome:
        try:
            r = self.session.post(
                f"{self.base_url}/",
                data=raw,
                headers={"Content-Type": "application/xml"},
                timeout=self.timeout,
            )
        except requests.RequestException as exc:
            return ValidationOutcome(
                valid=None, engine="kosit",
                transport_error=f"KoSIT unreachable: {exc}")
        # The KoSIT daemon signals the verdict through the HTTP status (200 for
        # accept, 4xx such as 406 for reject) but always returns a VARL report
        # body. So a non-200 with a report is a *verdict*, not a transport error.
        body = r.text or ""
        if "varlVersion" in body:
            return parse_kosit_report(body)
        return ValidationOutcome(
            valid=None, engine="kosit",
            transport_error=f"KoSIT HTTP {r.status_code}: {body[:200]}")


# Process-wide default clients so the validate_* helpers are cheap to call.
_default_client: InvoiceValidatorClient | None = None
_default_kosit: KositValidatorClient | None = None
_client_lock = threading.Lock()
# Nag only once per engine about being down, not per invoice.
_unavailable_warned: set[str] = set()


def get_client() -> InvoiceValidatorClient:
    global _default_client
    with _client_lock:
        if _default_client is None:
            _default_client = InvoiceValidatorClient()
        return _default_client


def get_kosit_client() -> KositValidatorClient:
    global _default_kosit
    with _client_lock:
        if _default_kosit is None:
            _default_kosit = KositValidatorClient()
        return _default_kosit


# --------------------------------------------------------------------------- #
# Folding an outcome into the fuzzer's Report
# --------------------------------------------------------------------------- #

def _apply_outcome(outcome: ValidationOutcome, report: Any, *, doc: str,
                   engine: str = "validator", secondary: bool = False) -> None:
    """Merge a :class:`ValidationOutcome` into a fuzzer ``Report``.

    ``report`` is the ``generate_invoices.Report`` dataclass (duck-typed here to
    avoid a hard import cycle): it exposes ``.errors``, ``.warnings`` and
    ``.anomalies`` lists.

    Severity policy mirrors the fuzzer's own: a *clean* invoice (no recorded
    anomalies) that the validator rejects is a generator bug -> error. On an
    *edge* invoice we deliberately sent something odd, so a rejection is expected
    -> record it as a warning to keep the signal clean.

    ``secondary`` downgrades everything to warnings/notices: this is a supporting
    second opinion (KoSIT on the XML embedded in a ZUGFeRD PDF that Mustang has
    already validated), so it should add signal without escalating severity or
    double-counting what the primary engine already flagged.
    """
    if report is None:
        return

    # Transport / availability problems: not an invoice verdict.
    if outcome.valid is None:
        msg = f"{doc}: {engine} validation unavailable ({outcome.transport_error})"
        if VALIDATOR_REQUIRED and not secondary:
            report.errors.append(msg)
        elif engine not in _unavailable_warned:
            _unavailable_warned.add(engine)
            report.warnings.append(
                msg + " -- set INVOICE_VALIDATOR_REQUIRED=1 to treat as error, "
                "or start it with `docker compose up -d`")
        return

    is_edge = bool(getattr(report, "anomalies", None))

    def emit_error(line: str) -> None:
        if secondary or is_edge:
            report.warnings.append(line)
        else:
            report.errors.append(line)

    # A KoSIT "no scenario matched": the document is not a recognizable
    # XRechnung. As a primary XRechnung check that is a real failure; as a
    # secondary check on a plain ZUGFeRD CII it is expected -> just a notice.
    if outcome.scenario_matched is False:
        note = f"{doc}: [{outcome.engine}] no matching XRechnung scenario"
        if secondary:
            if INCLUDE_NOTICES:
                report.warnings.append(note + " (embedded XML is not an XRechnung)")
        else:
            emit_error(note)
        return

    for f in outcome.findings:
        line = f"{doc}: {f.one_line()}"
        if f.severity == "error":
            emit_error(line)
        elif f.severity == "warning":
            report.warnings.append(line)
        elif INCLUDE_NOTICES:
            report.warnings.append(line)

    # If the engine says "invalid" but produced no error-level messages (e.g. a
    # PDF/A container failure surfaced only in the summary), don't lose it.
    if outcome.valid is False and not outcome.errors:
        line = (f"{doc}: [{outcome.engine}] verdict INVALID "
                f"(sections={outcome.section_status or 'n/a'})")
        emit_error(line)


# --------------------------------------------------------------------------- #
# Public validation entry points
# --------------------------------------------------------------------------- #
# Call these from generate_invoices.py. They accept the value straight from the
# API response (a base64 string) or raw bytes, run the cheap structural checks
# first, then the deep HTTP validation, and fold any findings into ``report``
# (when given). Each also returns the ValidationOutcome for standalone use.

def _coerce_bytes(document: Any) -> tuple[bytes | None, str | None, str | None]:
    """Normalize a response value to raw bytes.

    Returns ``(raw, warning, error)``: exactly one of the three is meaningful.
    ``warning`` means "nothing to validate" (missing field); ``error`` means the
    value was present but unusable (bad base64 / wrong type).
    """
    if document is None or document == "":
        return None, "missing from response", None
    if isinstance(document, (bytes, bytearray)):
        return bytes(document), None, None
    if isinstance(document, str):
        try:
            return base64.b64decode(document, validate=True), None, None
        except Exception:
            return None, None, "is not valid base64"
    return None, None, f"has unexpected type {type(document).__name__}"


def _early(report: Any, *, doc: str, section: str,
           warning: str | None = None, error: str | None = None) -> ValidationOutcome:
    """Record a pre-check result and build the matching outcome.

    ``warning`` means "nothing to validate" (missing field) -> no verdict;
    ``error`` means the value was present but unusable -> invalid.
    """
    if warning is not None:
        msg = f"{doc}: {warning}"
        if report is not None:
            report.warnings.append(msg)
        return ValidationOutcome(
            valid=None,
            findings=[Finding("warning", msg, section=section)])
    msg = f"{doc}: {error}"
    if report is not None:
        report.errors.append(msg)
    return ValidationOutcome(
        valid=False,
        findings=[Finding("error", msg, section=section)])


def validate_zugferd(pdf: Any, report: Any = None, *,
                     client: InvoiceValidatorClient | None = None,
                     kosit: "KositValidatorClient | None" = None,
                     secondary_kosit: bool = True) -> ValidationOutcome:
    """Validate a ZUGFeRD / Factur-X document -- the WHOLE hybrid PDF.

    Primary: Mustang checks PDF/A-3 conformance *and* the embedded XML
    (XML-Schema + EN16931 / profile Schematron), i.e. the file, not just the data.

    Secondary (``secondary_kosit=True``): the embedded XML is extracted and also
    run through the official KoSIT XRechnung validator. Its findings are folded
    in as warnings (a supporting second opinion); if the embedded XML is a plain
    ZUGFeRD CII that matches no XRechnung scenario, that is treated as a notice,
    not a failure.

    ``pdf``    the ``invoicePdf`` value from the API response (base64 string) or
               raw PDF bytes.
    ``report`` optional fuzzer ``Report``; findings are folded in when given. The
               primary ``ValidationOutcome`` (Mustang) is always returned.
    """
    raw, warn, err = _coerce_bytes(pdf)
    if warn:
        return _early(report, doc="invoicePdf", section="pdf", warning=warn)
    if err:
        return _early(report, doc="invoicePdf", section="pdf", error=err)
    if raw is None:
        return _early(report, doc="invoicePdf", section="pdf",
                      error="Raw value is None")
    if not raw.startswith(b"%PDF"):
        return _early(report, doc="invoicePdf", section="pdf",
                      error="does not start with %PDF")

    mustang = client or get_client()
    outcome = mustang.validate_bytes(raw, kind="pdf")
    if report is not None:
        _apply_outcome(outcome, report, doc="invoicePdf", engine="mustang")

    # Secondary: KoSIT on the embedded XML.
    if secondary_kosit:
        embedded = mustang.extract_embedded_xml(raw)
        if embedded is not None:
            kosit_outcome = (kosit or get_kosit_client()).validate_bytes(embedded)
            if report is not None:
                _apply_outcome(kosit_outcome, report,
                               doc="invoicePdf[embedded-xml]",
                               engine="kosit", secondary=True)
    return outcome


def validate_xrechnung(xml: Any, report: Any = None, *,
                       kosit: "KositValidatorClient | None" = None) -> ValidationOutcome:
    """Validate an XRechnung / CII XML document with the official KoSIT validator.

    KoSIT is the German B2G reference: it checks the XML against XML-Schema, the
    EN16931 rules and the XRechnung CIUS (BR-DE) rules, and returns an accept /
    reject assessment. A document that matches no XRechnung scenario is reported
    as a failure (it is not a recognizable XRechnung).

    ``xml``    the ``invoiceXml`` value from the API response (base64 string) or
               raw XML bytes.
    ``report`` optional fuzzer ``Report`` (see :func:`validate_zugferd`).
    """
    raw, warn, err = _coerce_bytes(xml)
    if warn:
        return _early(report, doc="invoiceXml", section="xml", warning=warn)
    if err:
        return _early(report, doc="invoiceXml", section="xml", error=err)
    if raw is None:
        return _early(report, doc="invoiceXml", section="xml", error="Raw value is None")
    try:
        ElementTree.fromstring(raw)
    except ElementTree.ParseError as exc:
        return _early(report, doc="invoiceXml", section="xml",
                      error=f"is not well-formed XML: {exc}")
    outcome = (kosit or get_kosit_client()).validate_bytes(raw)
    if report is not None:
        _apply_outcome(outcome, report, doc="invoiceXml", engine="kosit")
    return outcome


# --------------------------------------------------------------------------- #
# Standalone CLI: validate files or directories directly
# --------------------------------------------------------------------------- #

def _iter_targets(paths: list[str]) -> list[str]:
    import glob
    out: list[str] = []
    for p in paths:
        if os.path.isdir(p):
            for ext in ("*.pdf", "*.xml"):
                out.extend(sorted(glob.glob(os.path.join(p, "**", ext),
                                            recursive=True)))
        else:
            out.append(p)
    return out


def _main(argv: list[str]) -> int:
    import argparse
    parser = argparse.ArgumentParser(
        description="Validate ZUGFeRD/Factur-X PDFs (Mustang, whole PDF + KoSIT "
                    "on the embedded XML) or XRechnung/CII XML (KoSIT).")
    parser.add_argument("paths", nargs="+",
                        help="files and/or directories to validate")
    parser.add_argument("--mustang-url", default=MUSTANG_URL,
                        help=f"Mustang base URL (default {MUSTANG_URL})")
    parser.add_argument("--kosit-url", default=KOSIT_URL,
                        help=f"KoSIT base URL (default {KOSIT_URL})")
    parser.add_argument("--notices", action="store_true",
                        help="include NOTICE-level findings")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="print every finding, not just a summary line")
    args = parser.parse_args(argv)

    global INCLUDE_NOTICES, _default_client, _default_kosit
    if args.notices:
        INCLUDE_NOTICES = True # type: ignore
    _default_client = InvoiceValidatorClient(base_url=args.mustang_url)
    _default_kosit = KositValidatorClient(base_url=args.kosit_url)

    mustang_up = _default_client.health()
    kosit_up = _default_kosit.health()
    if not mustang_up:
        print(f"Mustang at {args.mustang_url} not reachable. "
              f"Start it with: docker compose up -d", file=sys.stderr)
    if not kosit_up:
        print(f"KoSIT at {args.kosit_url} not reachable. "
              f"Start it with: docker compose up -d", file=sys.stderr)
    if not (mustang_up or kosit_up):
        return 2

    targets = _iter_targets(args.paths)
    if not targets:
        print("no .pdf/.xml files found", file=sys.stderr)
        return 2

    bad = 0
    for path in targets:
        # Use a throwaway Report so findings get the same clean-invoice severity
        # policy the fuzzer applies, then read them back.
        report = _CliReport()
        try:
            outcome = _validate_path_into(path, report)
        except OSError as exc:
            print(f"SKIP  {path}: {exc}")
            continue
        verdict = ("VALID  " if outcome.valid else
                   "ERR    " if outcome.valid is None else "INVALID")
        print(f"{verdict} {path}  (errors={len(report.errors)} "
              f"warnings={len(report.warnings)})")
        if outcome.valid is not True:
            bad += 1
        shown = report.errors + (report.warnings if args.verbose else [])
        for line in shown:
            print(f"        {line}")
    print(f"\n{len(targets)} file(s), {bad} not-valid/unvalidatable")
    return 1 if bad else 0


@dataclass
class _CliReport:
    anomalies: list[str] = field(default_factory=list[str])
    errors: list[str] = field(default_factory=list[str])
    warnings: list[str] = field(default_factory=list[str])


def _validate_path_into(path: str, report: "_CliReport") -> ValidationOutcome:
    with open(path, "rb") as fh:
        raw = fh.read()
    if raw.startswith(b"%PDF"):
        return validate_zugferd(raw, report)
    return validate_xrechnung(raw, report)


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))