"""add email sending

Revision ID: 63212104ea02
Revises: 392f9648b590
Create Date: 2026-07-24 12:52:52.962439
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '63212104ea02'
down_revision: str | None = '392f9648b590'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'email_senders',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('label',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False
                  ),
        sa.Column('from_email',
                  sa.String(length=255),
                  nullable=False
                  ),
        sa.Column('from_name',
                  sa.String(length=255),
                  nullable=True
                  ),
        sa.Column('reply_to',
                  sa.String(length=255),
                  nullable=True
                  ),
        sa.Column('host',
                  sa.String(length=255),
                  nullable=False
                  ),
        sa.Column('port',
                  sa.Integer(),
                  nullable=False
                  ),
        sa.Column('security',
                  sa.String(length=16),
                  nullable=False),
        sa.Column('username',
                  sa.String(length=255),
                  nullable=True),
        sa.Column('password',
                  sa.Text(),
                  nullable=True
                  ),
        sa.Column('purposes',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('priority',
                  sa.Integer(),
                  nullable=False
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False
                  ),
        sa.Column('deleted_at',
                  sa.DateTime(timezone=True),
                  nullable=True
                  ),
        sa.Column('deleted_by',
                  sa.String(length=128),
                  nullable=True
                  ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'email_templates',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('locale',
                  sa.String(length=2),
                  nullable=False
                  ),
        sa.Column('label',
                  postgresql.JSONB(
                      astext_type=sa.Text()),
                  nullable=False
                  ),
        sa.Column('subject',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('preview_text',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('html',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('purposes',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('priority',
                  sa.Integer(),
                  nullable=False
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False
                  ),
        sa.Column('updated_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('deleted_at',
                  sa.DateTime(timezone=True),
                  nullable=True
                  ),
        sa.Column('deleted_by',
                  sa.String(length=128),
                  nullable=True
                  ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'email_template_files',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('email_template_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('file_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('type',
                  sa.String(length=256),
                  nullable=False
                  ),
        sa.Column('key',
                  sa.String(length=2048),
                  nullable=True
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False
                  ),
        sa.Column('deleted_at',
                  sa.DateTime(timezone=True),
                  nullable=True
                  ),
        sa.Column('deleted_by',
                  sa.String(length=128),
                  nullable=True
                  ),
        sa.ForeignKeyConstraint(['email_template_id'],
                                ['email_templates.id'],
                                ondelete='SET NULL'
                                ),
        sa.ForeignKeyConstraint(['file_id'],
                                ['files.id'],
                                ondelete='SET NULL'
                                ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'email_template_versions',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('email_template_id',
                  postgresql.UUID(
                      as_uuid=True),
                  nullable=True
                  ),
        sa.Column('locale',
                  sa.String(length=2),
                  nullable=False
                  ),
        sa.Column('label',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False
                  ),
        sa.Column('subject',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('previewText',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('html',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('purposes',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('priority',
                  sa.Integer(),
                  nullable=False
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False),
        sa.ForeignKeyConstraint(['email_template_id'],
                                ['email_templates.id'],
                                ondelete='SET NULL'
                                ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'emails',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('email_template_version_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('email_sender_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('locale',
                  sa.String(length=2),
                  nullable=False
                  ),
        sa.Column('to',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('cc',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('bcc',
                  postgresql.ARRAY(sa.Text()),
                  nullable=False
                  ),
        sa.Column('sender',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('subject',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('body',
                  sa.Text(),
                  nullable=False
                  ),
        sa.Column('status',
                  sa.Text(),
                  nullable=True
                  ),
        sa.Column('send_after',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('retry_after',
                  sa.DateTime(timezone=True),
                  nullable=True
                  ),
        sa.Column('retries',
                  sa.Integer(),
                  nullable=False
                  ),
        sa.Column('delivered_at',
                  sa.DateTime(timezone=True),
                  nullable=True
                  ),
        sa.Column('server_response',
                  sa.Text(),
                  nullable=True
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False
                  ),
        sa.ForeignKeyConstraint(['email_sender_id'],
                                ['email_senders.id'],
                                ondelete='SET NULL'
                                ),
        sa.ForeignKeyConstraint(['email_template_version_id'],
                                ['email_template_versions.id'],
                                ondelete='SET NULL'
                                ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'email_attachments',
        sa.Column('id',
                  postgresql.UUID(as_uuid=True),
                  nullable=False
                  ),
        sa.Column('email_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('file_id',
                  postgresql.UUID(as_uuid=True),
                  nullable=True
                  ),
        sa.Column('file_name',
                  sa.String(length=2048),
                  nullable=False
                  ),
        sa.Column('created_at',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=False
                  ),
        sa.Column('created_by',
                  sa.String(length=128),
                  nullable=False
                  ),
        sa.ForeignKeyConstraint(['email_id'],
                                ['emails.id'],
                                ondelete='SET NULL'
                                ),
        sa.ForeignKeyConstraint(['file_id'],
                                ['files.id'],
                                ondelete='SET NULL'
                                ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('email_attachments')
    op.drop_table('emails')
    op.drop_table('email_template_versions')
    op.drop_table('email_template_files')
    op.drop_table('email_templates')
    op.drop_table('email_senders')
